const VEHICLE_STATUSES = ["AVAILABLE", "ON_TRIP", "IN_SHOP", "RETIRED"];
const DRIVER_STATUSES = ["AVAILABLE", "ON_TRIP", "OFF_DUTY", "SUSPENDED"];
const TRIP_STATUSES = ["DRAFT", "DISPATCHED", "COMPLETED", "CANCELLED"];
const MAINTENANCE_STATUSES = ["ACTIVE", "COMPLETED"];
const EXPENSE_TYPES = ["TOLL", "MAINTENANCE", "OTHER"];

module.exports = {
  VEHICLE_STATUSES,
  DRIVER_STATUSES,
  TRIP_STATUSES,
  MAINTENANCE_STATUSES,
  EXPENSE_TYPES,
};
